/**
 * Serves the local Playwright HTML report at `/admin/playwright/*`.
 *
 * Files come from `playwright-report/` in this repo (generated by `yarn playwright test`).
 * ADMIN cookie only — no API proxy needed (unlike Allure, which lives on the Jetty host).
 *
 * The HTML report follows OS theme by default; we force light so it matches the storefront.
 */
import type { LoaderFunctionArgs } from "@remix-run/node";
import { redirect } from "@remix-run/node";
import { createReadStream, existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { Readable } from "node:stream";
import { readSessionUser } from "~/utils/session.server";

const REPORT_ROOT = path.resolve(process.cwd(), "playwright-report");

const LIGHT_THEME_BOOT = `<script>try{var t=localStorage.getItem("theme");if(!t||t==="system")localStorage.setItem("theme","light-mode")}catch(e){}</script>`;

function contentTypeFor(fileName: string): string {
  const lower = fileName.toLowerCase();
  if (lower.endsWith(".html")) return "text/html; charset=utf-8";
  if (lower.endsWith(".js")) return "application/javascript; charset=utf-8";
  if (lower.endsWith(".css")) return "text/css; charset=utf-8";
  if (lower.endsWith(".json") || lower.endsWith(".webmanifest")) {
    return "application/json; charset=utf-8";
  }
  if (lower.endsWith(".svg")) return "image/svg+xml";
  if (lower.endsWith(".png")) return "image/png";
  if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) return "image/jpeg";
  if (lower.endsWith(".woff2")) return "font/woff2";
  if (lower.endsWith(".woff")) return "font/woff";
  if (lower.endsWith(".zip")) return "application/zip";
  return "application/octet-stream";
}

export async function loader({ request, params }: LoaderFunctionArgs) {
  const user = await readSessionUser(request);
  if (!user) return redirect("/");
  if (user.role !== "ADMIN") {
    throw new Response("Admins only", { status: 403 });
  }

  const splat = params["*"] || "index.html";
  const target = path.resolve(REPORT_ROOT, splat);
  if (!target.startsWith(REPORT_ROOT + path.sep) && target !== REPORT_ROOT) {
    throw new Response("Not found", { status: 404 });
  }
  if (!existsSync(target) || !statSync(target).isFile()) {
    throw new Response(
      "Playwright report not found. Run: yarn playwright test   (writes playwright-report/)",
      { status: 404 }
    );
  }

  const fileName = path.basename(target);
  if (fileName.endsWith(".html")) {
    let html = readFileSync(target, "utf8");
    if (!html.includes('localStorage.setItem("theme","light-mode")')) {
      html = html.replace(/<head>/i, `<head>${LIGHT_THEME_BOOT}`);
    }
    html = html
      .replace(/var uo=`system`/g, "var uo=`light-mode`")
      .replace(/content=['"]dark light['"]/g, "content='light'");
    return new Response(html, {
      status: 200,
      headers: {
        "Content-Type": contentTypeFor(fileName),
        "Cache-Control": "no-store",
      },
    });
  }

  const body = Readable.toWeb(createReadStream(target)) as ReadableStream;
  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": contentTypeFor(fileName),
      "Cache-Control": "no-store",
    },
  });
}
